[functions]
  directory = "netlify/functions"          
  node_bundler = "esbuild"                 
  external_node_modules = ["jsdom", "@mozilla/readability", "@netlify/blobs"]
  included_files = [
    "node_modules/jsdom/**",
    "node_modules/@mozilla/readability/**",
    "node_modules/@netlify/blobs/**"
  ]


  [functions."nana_explain"]
  timeout = 20

[build]
command = "npm run build"
publish = "dist"



[[redirects]]
  from = "/articles"
  to = "/.netlify/functions/articles"
  status = 200







